$(document).ready(function(){
    $('.close_btn').click(function(){
        $('#members_click').removeClass('active');
        $('.click_layout').removeClass('active');
    });
    $('#member1').click(function(){
        $('#members_click').addClass('active');
        $('#member1_layout').addClass('active');
    });
    $('#member2').click(function(){
        $('#members_click').addClass('active');
        $('#member2_layout').addClass('active');
    });
    $('#member3').click(function(){
        $('#members_click').addClass('active');
        $('#member3_layout').addClass('active');
    });
    $('#member4').click(function(){
        $('#members_click').addClass('active');
        $('#member4_layout').addClass('active');
    });
    $('#member5').click(function(){
        $('#members_click').addClass('active');
        $('#member5_layout').addClass('active');
    });
    $('#member6').click(function(){
        $('#members_click').addClass('active');
        $('#member6_layout').addClass('active');
    });
    $('#member7').click(function(){
        $('#members_click').addClass('active');
        $('#member7_layout').addClass('active');
    });
    $('#member8').click(function(){
        $('#members_click').addClass('active');
        $('#member8_layout').addClass('active');
    });
    $('#member9').click(function(){
        $('#members_click').addClass('active');
        $('#member9_layout').addClass('active');
    });
    $('#member10').click(function(){
        $('#members_click').addClass('active');
        $('#member10_layout').addClass('active');
    });
    $('#member11').click(function(){
        $('#members_click').addClass('active');
        $('#member11_layout').addClass('active');
    });
});